appName: example
enableHiveSupport: true
flow:
  - type: read
    sources:
      - format: csv
        fromPath: /raw/kaggle/world_economy/corruption.csv
        options:
          header: true
        schema: |
          {"type":"struct","fields":[{"name":"country","type":"string","nullable":true,"metadata":{}},{"name":"annual_income","type":"integer","nullable":true,"metadata":{}},{"name":"corruption_index","type":"integer","nullable":true,"metadata":{}}]}
        tempView: corruption
  - type: query
    sqls:
      - sql: set spark.sql.session.timeZone = UTC
      - tempView: corruption_final
        cache: true
        sql: |
          WITH
          corruption_with_time AS (
            SELECT
              country,
              annual_income,
              corruption_index,
              TIMESTAMP(UNIX_SECONDS(CURRENT_TIMESTAMP()) + cast(rand()*100000 AS INT)) AS updated_time
              CAST(RAND()*10 AS INT) as rand_key
            from corruption),
          SELECT
            country,
            annual_income,
            corruption_index,
            updated_time,
            TO_DATE(updated_time) AS updated_date,
            rand_key
          FROM corruption_with_time
  - type: show
    items:
      - tempView: corruption_with_time
        limit: 50
  - type: write
    sinks:
      - format: delta
        fromTempViewOrTable: corruption_final
        toTable: world_economy_dev.corruption_delta
        saveMode: overwrite
